services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    command: npx next dev --port 3001
    ports:
      - "${APP_PORT}:3001"
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
