/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        'bg-primary': 'var(--bg-primary)',
        'bg-secondary': 'var(--bg-secondary)',
        'bg-tertiary': 'var(--bg-tertiary)',
        surface: 'var(--surface)',
        'surface-strong': 'var(--surface-strong)',
        'surface-base': 'var(--surface-base)',
        'surface-sunken': 'var(--surface-sunken)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-tertiary': 'var(--text-tertiary)',
        'text-inverse': 'var(--text-inverse)',
        accent: 'var(--accent-primary)',
        'accent-hover': 'var(--accent-primary-hover)',
        'accent-subtle': 'var(--accent-primary-subtle)',
        'border-light': 'var(--border-light)',
        'border-default': 'var(--border-default)',
        'border-strong': 'var(--border-strong)',
        error: 'var(--error)',
        'error-subtle': 'var(--error-subtle)',
        success: 'var(--success)',
        'success-subtle': 'var(--success-subtle)',
        warning: 'var(--warning)',
        'warning-subtle': 'var(--warning-subtle)',
        info: 'var(--info)',
        'info-subtle': 'var(--info-subtle)',
        'nav-bg': 'var(--nav-bg)',
        'nav-hover': 'var(--nav-hover-bg)',
        'nav-active-bg': 'var(--nav-active-bg)',
        'nav-active': 'var(--nav-active)',
        'topbar-bg': 'var(--topbar-bg)',
        'topbar-border': 'var(--topbar-border)',
        'dropdown-bg': 'var(--dropdown-bg)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        dropdown: 'var(--dropdown-shadow)',
      },
      height: { topbar: 'var(--topbar-h)' },
      minHeight: { topbar: 'var(--topbar-h)' },
      width: {
        sidebar: 'var(--sidebar-w)',
        'sidebar-collapsed': 'var(--sidebar-collapsed-w)',
      },
      minWidth: { sidebar: 'var(--sidebar-w)' },
      fontFamily: {
        display: ['var(--font-display)', 'sans-serif'],
        body: ['var(--font-body)', 'sans-serif'],
      },
      spacing: {
        topbar: 'var(--topbar-h)',
        sidebar: 'var(--sidebar-w)',
        'sidebar-collapsed': 'var(--sidebar-collapsed-w)',
      },
      transitionDuration: { DEFAULT: '180ms' },
    },
  },
  plugins: [],
}
